services:
  web:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
  
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "5500:80"
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  postgres_data: